@BookStoreApi_HostAddress = https://localhost:7006

GET {{BookStoreApi_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{BookStoreApi_HostAddress}}/api/books

###

POST {{BookStoreApi_HostAddress}}/api/books
Content-Type: application/json

{ "Name": "Design Patterns 2", "Price": 54.93, "Category": "Computers", "Author": "Ralph Johnson" }
###{ "Name": "Clean Code 2", "Price": 43.15, "Category": "Computers","Author": "Robert C. Martin" }

###
